from building import *

group = []

if not GetDepend(['RT_USING_RTC']):
    Return('group')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include']

src = ['rtc.c']

if GetDepend(['RT_USING_ALARM']):
    src += ['alarm.c']

if GetDepend(['RT_USING_SOFT_RTC']):
    src += ['soft_rtc.c']

if GetDepend(['RT_USING_DM']):
    src += ['rtc_dm.c']

if GetDepend(['RT_RTC_GOLDFISH']):
    src += ['rtc-goldfish.c']

if GetDepend(['RT_RTC_HYM8563']):
    src += ['rtc-hym8563.c']

if GetDepend(['RT_RTC_PL031']):
    src += ['rtc-pl031.c']

if GetDepend(['RT_RTC_RK8XX']):
    src += ['rtc-rk8xx.c']

if GetDepend(['RT_RTC_RK_TIMER']):
    src += ['rtc-rk_timer.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
