# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
src     += Glob('expired/*.c')
src     += Glob('virtio/*.c')

CPPPATH = [cwd]
CPPPATH += [cwd + '/expired']
CPPPATH += [cwd + '/virtio']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
