from building import *

group = []

if not GetDepend(['RT_USING_ADC']):
    Return('group')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include']

src = ['adc.c']

if GetDepend(['RT_ADC_ROCKCHIP_SARADC']):
    src += ['adc-rockchip_saradc.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
