from building import *

group = []

if not GetDepend(['RT_USING_MBOX']):
    Return('group')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include']

src = ['mailbox.c']

if GetDepend(['RT_MBOX_BCM2835']):
    src += ['mailbox-bcm2835.c']

if GetDepend(['RT_MBOX_ROCKCHIP']):
    src += ['mailbox-rockchip.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
