from building import *

group = []

if not GetDepend(['RT_USING_WDT']):
    Return('group')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include']

src = ['watchdog.c']

if GetDepend(['RT_WDT_BCM2835']):
    src += ['watchdog-bcm2835.c']

if GetDepend(['RT_WDT_DW']):
    src += ['watchdog-dw.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
