from building import *

group = []

if not GetDepend(['RT_USING_PWM']):
    Return('group')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include']

src = ['pwm.c']

if GetDepend(['RT_PWM_ROCKCHIP']):
    src += ['pwm-rockchip.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
