# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = []
CPPPATH = [cwd]

src += ['af_unix.c']

group = DefineGroup('SAL', src, depend = ['RT_USING_SAL', 'SAL_USING_AF_UNIX', 'RT_USING_DFS_V2'], CPPPATH = CPPPATH)

Return('group')
