from building import *

group = []

if not GetDepend(['RT_USING_REGULATOR']):
    Return('group')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include']

src = ['regulator.c', 'regulator-fixed.c', 'regulator_dm.c']

if GetDepend(['RT_REGULATOR_GPIO']):
    src += ['regulator-gpio.c']

if GetDepend(['RT_REGULATOR_RK8XX']):
    src += ['regulator-rk8xx.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
