from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]
src = []

if GetDepend(['RT_MFD_SYSCON']):
    src += ['mfd-syscon.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
