from building import *

group = []

if not GetDepend(['RT_USING_HWSPINLOCK']):
    Return('group')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include']

src = ['hwspinlock.c']

if GetDepend(['RT_HWSPINLOCK_ROCKCHIP']):
    src += ['hwspinlock-rockchip.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
