from building import *

group = []

if not GetDepend(['RT_PCI_MSI']):
    Return('group')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../../include']

src = ['msi.c', 'msi_dev.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
