from building import *

group = []

if not GetDepend(['RT_USING_VIRTIO']):
    Return('group')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include']

src = ['virtio.c', 'virtio_queue.c']

if GetDepend(['RT_VIRTIO_TRANSPORT_MMIO']):
    src += ['virtio_mmio.c']

if GetDepend(['RT_VIRTIO_TRANSPORT_PCI']):
    src += ['virtio_pci.c', 'virtio_pci_legacy.c', 'virtio_pci_modern.c']

if GetDepend(['RT_VIRTIO_NET']):
    src += ['virtio-net.c']

if GetDepend(['RT_VIRTIO_BLK']):
    src += ['virtio-blk.c']

if GetDepend(['RT_VIRTIO_CONSOLE']):
    src += ['virtio-console.c']

if GetDepend(['RT_VIRTIO_RNG']):
    src += ['virtio-rng.c']

# if GetDepend(['RT_VIRTIO_GPU']):
#     src += ['virtio-gpu.c']

if GetDepend(['RT_VIRTIO_INPUT']):
    src += ['virtio-input.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
