# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = []
CPPPATH = [cwd, cwd + '/port']

src += Glob('*.c')
src += Glob('port/*.c')

src += Glob('platform/rk/*.c')

group = DefineGroup('Drivers', src, depend = [], CPPPATH = CPPPATH)

objs = [group]

Return('objs')
