Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
src = []

group = []
if not GetDepend(['RT_USING_NET']):
    Return('group')

# The set of source files associated with this SConscript file.
path = [cwd + '/../include']

if GetDepend(['RT_USING_DM']):
    src += ['net_dm.c']

if GetDepend(['RT_USING_DWC_EQOS']):
    src += ['dwc_eth_qos.c']

if GetDepend(['RT_USING_DWC_EQOS_ROCKCHIP']):
    src += ['dwc_eth_qos_rk.c']

group = DefineGroup('DeviceDrivers', src, depend = ['RT_USING_NET'], CPPPATH = path)
objs = []

for d in os.listdir(cwd):
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))
objs = objs + group

Return('objs')
