from building import *

group = []
objs = []

if not GetDepend(['RT_USING_SERIAL']):
    Return('group')

cwd = GetCurrentDir()
list = os.listdir(cwd)
CPPPATH = [cwd + '/../include']

src = []

if GetDepend(['RT_USING_SERIAL_V2']):
    src += ['serial_v2.c']
else:
    src += ['serial.c']

if GetDepend(['RT_USING_DM']):
    src += ['serial_dm.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)


Return('group')
